apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: drop-backend-secrets
spec:
  provider: aws
  parameters:
    region: ap-northeast-2
    objects: |
      - objectName: "drop/backend/db-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db-username
          - path: password
            objectAlias: db-password
          - path: host
            objectAlias: db-host
          - path: port
            objectAlias: db-port
          - path: database
            objectAlias: db-database
      - objectName: "drop/backend/oauth-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: googleClientId
            objectAlias: google-client-id
          - path: googleClientSecret
            objectAlias: google-client-secret
      - objectName: "drop/backend/jwt-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: secretKey
            objectAlias: jwt-secret-key
      - objectName: "drop/backend/aes-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: secretKey
            objectAlias: aes-secret-key
      - objectName: "drop/backend/redis-connection"
        objectType: "secretsmanager"
        jmesPath:
          - path: host
            objectAlias: redis-host
          - path: port
            objectAlias: redis-port
      - objectName: "drop/backend/kakao-api"
        objectType: "secretsmanager"
        jmesPath:
          - path: key
            objectAlias: kakao-api-key
  secretObjects:
  - secretName: drop-backend-secrets-k8s
    type: Opaque
    data:
    - objectName: db-username
      key: database-username
    - objectName: db-password
      key: database-password
    - objectName: db-host
      key: database-host
    - objectName: db-port
      key: database-port
    - objectName: db-database
      key: database-name
    - objectName: google-client-id
      key: google-client-id
    - objectName: google-client-secret
      key: google-client-secret
    - objectName: jwt-secret-key
      key: jwt-secret-key
    - objectName: aes-secret-key
      key: aes-secret-key
    - objectName: redis-host
      key: redis-host
    - objectName: redis-port
      key: redis-port
    - objectName: kakao-api-key
      key: kakao-api-key
