divisions:
  서울특별시:
    level: "시도"
    children:
      강남구:
        level: "시군구"
        children:
          - "역삼동"
          - "삼성동"
          - "청담동"
          - "논현동"
          - "압구정동"
          - "신사동"
          - "도곡동"
          - "대치동"
          - "개포동"
          - "세곡동"
      강동구:
        level: "시군구"
        children:
          - "천호동"
          - "성내동"
          - "길동"
          - "명일동"
          - "암사동"
          - "강일동"
          - "상일동"
          - "둔촌동"
      강북구:
        level: "시군구"
        children:
          - "미아동"
          - "번동"
          - "수유동"
          - "우이동"
      강서구:
        level: "시군구"
        children:
          - "염창동"
          - "등촌동"
          - "화곡동"
          - "가양동"
          - "마곡동"
          - "방화동"
      관악구:
        level: "시군구"
        children:
          - "봉천동"
          - "신림동"
          - "남현동"
      광진구:
        level: "시군구"
        children:
          - "중곡동"
          - "능동"
          - "구의동"
          - "광장동"
          - "자양동"
          - "화양동"
          - "군자동"
      구로구:
        level: "시군구"
        children:
          - "구로동"
          - "고척동"
          - "개봉동"
          - "오류동"
          - "항동"
          - "신도림동"
      금천구:
        level: "시군구"
        children:
          - "가산동"
          - "독산동"
          - "시흥동"
      노원구:
        level: "시군구"
        children:
          - "월계동"
          - "공릉동"
          - "하계동"
          - "상계동"
          - "중계동"
      도봉구:
        level: "시군구"
        children:
          - "쌍문동"
          - "방학동"
          - "창동"
          - "도봉동"
      동대문구:
        level: "시군구"
        children:
          - "용두동"
          - "제기동"
          - "전농동"
          - "답십리동"
          - "장안동"
          - "청량리동"
          - "회기동"
          - "이문동"
          - "휘경동"
      동작구:
        level: "시군구"
        children:
          - "노량진동"
          - "상도동"
          - "흑석동"
          - "사당동"
          - "대방동"
          - "신대방동"
      마포구:
        level: "시군구"
        children:
          - "합정동"
          - "상암동"
          - "연남동"
          - "망원동"
          - "성산동"
          - "상수동"
          - "서교동"
          - "홍익동"
      서대문구:
        level: "시군구"
        children:
          - "충정로동"
          - "북아현동"
          - "신촌동"
          - "연희동"
          - "홍제동"
          - "남가좌동"
          - "북가좌동"
      서초구:
        level: "시군구"
        children:
          - "서초동"
          - "잠원동"
          - "반포동"
          - "방배동"
          - "양재동"
          - "내곡동"
      성동구:
        level: "시군구"
        children:
          - "성수동"
          - "행당동"
          - "응봉동"
          - "금호동"
          - "옥수동"
          - "왕십리동"
          - "마장동"
          - "사근동"
      성북구:
        level: "시군구"
        children:
          - "성북동"
          - "삼선동"
          - "동선동"
          - "돈암동"
          - "안암동"
          - "보문동"
          - "정릉동"
          - "길음동"
          - "종암동"
          - "월곡동"
          - "장위동"
          - "석관동"
      송파구:
        level: "시군구"
        children:
          - "잠실동"
          - "풍납동"
          - "송파동"
          - "석촌동"
          - "삼전동"
          - "가락동"
          - "문정동"
          - "장지동"
          - "방이동"
          - "오금동"
          - "거여동"
          - "마천동"
      양천구:
        level: "시군구"
        children:
          - "목동"
          - "신월동"
          - "신정동"
      영등포구:
        level: "시군구"
        children:
          - "영등포동"
          - "여의도동"
          - "당산동"
          - "문래동"
          - "양평동"
          - "신길동"
          - "대림동"
          - "도림동"
      용산구:
        level: "시군구"
        children:
          - "이태원동"
          - "한남동"
          - "서빙고동"
          - "보광동"
          - "용산동"
          - "원효로동"
          - "효창동"
          - "청파동"
          - "남영동"
      은평구:
        level: "시군구"
        children:
          - "녹번동"
          - "불광동"
          - "갈현동"
          - "구산동"
          - "대조동"
          - "응암동"
          - "역촌동"
          - "신사동"
          - "증산동"
          - "수색동"
          - "진관동"
      종로구:
        level: "시군구"
        children:
          - "종로동"
          - "숭인동"
          - "혜화동"
          - "명륜동"
          - "창신동"
          - "평창동"
          - "무악동"
          - "교남동"
          - "사직동"
      중구:
        level: "시군구"
        children:
          - "을지로동"
          - "명동"
          - "필동"
          - "장충동"
          - "광희동"
          - "신당동"
          - "황학동"
          - "중림동"
      중랑구:
        level: "시군구"
        children:
          - "면목동"
          - "상봉동"
          - "중화동"
          - "묵동"
          - "망우동"
          - "신내동"

  경기도:
    level: "시도"
    children:
      수원시:
        level: "시군구"
        children:
          장안구:
            level: "구"
            children:
              - "정자동"
              - "영화동"
              - "송죽동"
              - "조원동"
              - "파장동"
              - "이목동"
              - "율전동"
          권선구:
            level: "구"
            children:
              - "권선동"
              - "세류동"
              - "평동"
              - "서둔동"
              - "구운동"
              - "금곡동"
              - "호매실동"
          팔달구:
            level: "구"
            children:
              - "인계동"
              - "매산동"
              - "우만동"
              - "화서동"
              - "매교동"
              - "영동"
          영통구:
            level: "구"
            children:
              - "영통동"
              - "매탄동"
              - "원천동"
              - "이의동"
              - "하동"
              - "신동"
      성남시:
        level: "시군구"
        children:
          수정구:
            level: "구"
            children:
              - "신흥동"
              - "태평동"
              - "수진동"
              - "단대동"
              - "산성동"
              - "복정동"
          중원구:
            level: "구"
            children:
              - "성남동"
              - "금광동"
              - "은행동"
              - "상대원동"
              - "여수동"
              - "하대원동"
          분당구:
            level: "구"
            children:
              - "분당동"
              - "수내동"
              - "서현동"
              - "정자동"
              - "판교동"
              - "야탑동"
              - "이매동"
              - "삼평동"
      고양시:
        level: "시군구"
        children:
          덕양구:
            level: "구"
            children:
              - "주교동"
              - "원당동"
              - "화정동"
              - "행신동"
              - "능곡동"
              - "향동동"
          일산동구:
            level: "구"
            children:
              - "백석동"
              - "마두동"
              - "장항동"
              - "정발산동"
              - "풍동"
              - "식사동"
          일산서구:
            level: "구"
            children:
              - "주엽동"
              - "대화동"
              - "탄현동"
              - "일산동"
              - "덕이동"
      용인시:
        level: "시군구"
        children:
          처인구:
            level: "구"
            children:
              - "역삼동"
              - "삼가동"
              - "남동"
              - "유방동"
              - "김량장동"
          기흥구:
            level: "구"
            children:
              - "구갈동"
              - "상갈동"
              - "보라동"
              - "신갈동"
              - "영덕동"
              - "구성동"
              - "마북동"
              - "동백동"
          수지구:
            level: "구"
            children:
              - "풍덕천동"
              - "죽전동"
              - "동천동"
              - "신봉동"
              - "성복동"
              - "상현동"

  부산광역시:
    level: "시도"
    children:
      해운대구:
        level: "시군구"
        children:
          - "우동"
          - "중동"
          - "좌동"
          - "송정동"
          - "반여동"
          - "재송동"
      수영구:
        level: "시군구"
        children:
          - "광안동"
          - "민락동"
          - "수영동"
          - "망미동"
          - "남천동"
      부산진구:
        level: "시군구"
        children:
          - "부전동"
          - "전포동"
          - "양정동"
          - "개금동"
          - "범전동"
          - "연지동"

  대구광역시:
    level: "시도"
    children:
      수성구:
        level: "시군구"
        children:
          - "범어동"
          - "만촌동"
          - "수성동"
          - "황금동"
          - "중동"
          - "상동"
          - "두산동"
          - "지산동"
      달서구:
        level: "시군구"
        children:
          - "월성동"
          - "진천동"
          - "용산동"
          - "상인동"
          - "도원동"
          - "본리동"
          - "장기동"
          - "감삼동"

  인천광역시:
    level: "시도"
    children:
      연수구:
        level: "시군구"
        children:
          - "연수동"
          - "청학동"
          - "동춘동"
          - "옥련동"
          - "선학동"
          - "송도동"
      남동구:
        level: "시군구"
        children:
          - "구월동"
          - "간석동"
          - "만수동"
          - "장수동"
          - "서창동"
          - "논현동"
      부평구:
        level: "시군구"
        children:
          - "부평동"
          - "산곡동"
          - "청천동"
          - "삼산동"
          - "갈산동"
          - "십정동"
