apiVersion: v1
kind: ServiceAccount
metadata:
  name: drop-backend-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::441070253196:role/eksctl-backend-api-dev-eks-addon-iamserviceac-Role1-5ORuHEVEDnMh
