apiVersion: v1
kind: Service
metadata:
  name: drop-backend-service
  labels:
    app: drop-backend
spec:
  type: LoadBalancer
  selector:
    app: drop-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  sessionAffinity: None
